### ISSUE TITLE
Missing Model File in Local Implementation?

### ISSUE THREAD

**Issue by KiranTen63** [srijitseal/DILI_Predictor#3]
Hi, thanks for this incredible work!

I installed the software quite easily using pip, and was able to run dilipred -h without any issues. However, when I try to run predictions from the CLI using a smiles string, I get an error asking for `bestlivmodel_2_model.sav` which does not appear to be one of the ones included in the model files that were made available for download? Or I may just not be looking in the right place. Any help would be greatly appreciated!

Thanks,

Kiran

**Comment by Manas02** [comment]
Please report the entire error stack and version of python used / environment freeze.

**Comment by srijitseal** [comment]
Also please me know where you downloaded the local implementation from? Is
it from the Zenodo link on broad.io/DILIPredictor?

(Then I’ll have to take a look at the files there, and it’s nothing to do
with the pip install package @Manas)

Thanks a lot!

**Comment by KiranTen63** [comment]
I'm using Python 3.8, which I realize is not the recommended version, but I think that is a separate issue.
From installing the pip package, no model files were included, so I downloaded the local implementation from https://github.com/srijitseal/DILI/raw/main/local_implementation.zip .

Here is the traceback 

`Traceback (most recent call last):
  File "/home/kiran/miniconda3/envs/aevs2/bin/dilipred", line 8, in <module>
    sys.exit(main())
  File "/home/kiran/miniconda3/envs/aevs2/lib/python3.8/site-packages/dilipred/main.py", line 410, in main
    result = dili_predictor.predict(args.smiles)
  File "/home/kiran/miniconda3/envs/aevs2/lib/python3.8/site-packages/dilipred/main.py", line 300, in predict
    test_mfp_Mordred_liv = predict_liv_all(test_mfp_Mordred)
  File "/home/kiran/miniconda3/envs/aevs2/lib/python3.8/site-packages/dilipred/main.py", line 226, in predict_liv_all
    y_proba = predict_individual_liv_data(data_dummy, features, endpoint)
  File "/home/kiran/miniconda3/envs/aevs2/lib/python3.8/site-packages/dilipred/main.py", line 182, in predict_individual_liv_data
    with open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/kiran/miniconda3/envs/aevs2/lib/python3.8/site-packages/dilipred/models/bestlivmodel_2_model.sav'
`

**Comment by Manas02** [comment]
[Local implementation](https://github.com/srijitseal/DILI/raw/main/local_implementation.zip) has models but that has nothing to do with the PyPI installable package. The models come with the package. Please use an env with specified python version. 
It is not supposed to be used with python 3.8 which is due to reach its scheduled upstream end-of-life in October 2024.

**Comment by KiranTen63** [comment]
Ah ok, reinstalling to a different environment with python 3.10 worked just fine. Interesting that the models were not included in the pip install for python 3.8 even though the code was able to run still. Thanks for the quick responses, and thank you again for your significant contribution to the field!
